export * as trendings from '@/api/rest/trendings'
export * as readme from '@/api/rest/readme'
export * as user from '@/api/rest/user'
export * as starred from '@/api/rest/starred'
export * as issues from '@/api/rest/issues'
